FROM python:3.9

ENV MLFLOW_VERSION 2.10.2
ENV TERM linux
ENV BUCKET bucket

RUN pip install mlflow==$MLFLOW_VERSION
RUN pip install google-cloud-storage
RUN mkdir -p /mlflow/

EXPOSE 5000

CMD mlflow server \
  --default-artifact-root gs://nifty-acolyte-415508/mlflow-plv \
  --host 0.0.0.0